import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');

const frontendDataPath = path.join(ROOT, 'src', 'data', 'properties.ts');
const outDir = path.join(ROOT, 'server', 'prisma', 'seed-data');
const outPath = path.join(outDir, 'projects.seed.ts');

const source = readFileSync(frontendDataPath, 'utf8');

const assetImportRe = /^import\s+(\w+)\s+from\s+'\.\.\/assets\/(.+?\.webp)';\s*$/gm;

const assets = new Map();
for (const match of source.matchAll(assetImportRe)) {
  const [, alias, assetPath] = match;
  assets.set(alias, `assets/${assetPath}`);
}

if (assets.size === 0) {
  console.error('No asset imports found in src/data/properties.ts — aborting.');
  process.exit(1);
}

const aliasRe = new RegExp(`\\b(${[...assets.keys()].join('|')})\\b`, 'g');

let body = source
  .replace(assetImportRe, '')
  .replace(/^import type \{ Property \}.*$/m, '')
  .replace('export const properties: Property[] =', 'export const properties: SeedProject[] =');

const exportIndex = body.indexOf('export const properties: SeedProject[] =');
if (exportIndex === -1) {
  console.error('Could not locate properties export in src/data/properties.ts — aborting.');
  process.exit(1);
}

const equalsIndex = body.indexOf('=', exportIndex);
const arrayStart = body.indexOf('[', equalsIndex);

let depth = 0;
let arrayEnd = -1;
for (let i = arrayStart; i < body.length; i++) {
  const ch = body[i];
  if (ch === '[') depth += 1;
  else if (ch === ']') {
    depth -= 1;
    if (depth === 0) {
      arrayEnd = i;
      break;
    }
  }
}
if (arrayEnd === -1) {
  console.error('Could not balance the properties array brackets — aborting.');
  process.exit(1);
}

const arrayBody = body.slice(arrayStart, arrayEnd + 1);

body = body
  .slice(0, arrayStart)
  .concat(arrayBody)
  .replace(aliasRe, (alias) => {
    const assetPath = assets.get(alias);
    return assetPath ? JSON.stringify(assetPath) : alias;
  })
  .trim();

const header = `// AUTO-GENERATED by scripts/sync-data.mjs — DO NOT EDIT BY HAND.
// Source of truth: frontend src/data/properties.ts (run \`npm run db:sync-data\` to regenerate).
// Image values are frontend asset paths (Phase 4 media pipeline will upgrade them to /uploads URLs).

export interface SeedUnit {
  id: string;
  unitNumber: string;
  floorNumber: number;
  floorNameAr: string;
  floorNameEn?: string;
  sectionAr?: string;
  type: 'showroom' | 'office' | 'apartment' | 'warehouse' | 'outdoor';
  typeAr: string;
  typeEn?: string;
  area: number;
  priceLabel?: string;
  status: 'available' | 'reserved' | 'rented' | 'sold';
  statusAr: string;
  statusEn?: string;
  features?: string[];
  featuresEn?: string[];
}

export interface SeedFloor {
  floorNumber: number;
  floorNameAr: string;
  floorNameEn: string;
  descriptionAr?: string;
  descriptionEn?: string;
  totalArea?: number;
  units: SeedUnit[];
}

export interface SeedProject {
  id: number;
  type: 'logistics' | 'commercial' | 'office' | 'residential';
  typeAr: string;
  typeEn?: string;
  title: string;
  titleEn?: string;
  price?: number;
  priceLabel?: string;
  priceType: string;
  priceTypeEn?: string;
  status?: string;
  statusEn?: string;
  area: number;
  rooms?: number;
  bathrooms?: number;
  units?: string;
  unitsEn?: string;
  city: string;
  cityEn?: string;
  image: string;
  gallery?: string[];
  description?: string;
  descriptionEn?: string;
  badge?: string;
  badgeEn?: string;
  features?: string[];
  featuresEn?: string[];
  videoUrl?: string;
  virtualTour3dAvailable?: boolean;
  locationHighlightsAr?: string[];
  locationHighlightsEn?: string[];
  floors?: SeedFloor[];
  lat?: number;
  lng?: number;
}

`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, `${header}${body}\n`);

console.log(`Synced ${assets.size} asset references -> ${outPath}`);